package kmp.shared.sampletabbar.presentation.ui

import platform.UIKit.UIViewController

// Originally generated by Touchlab's [compose-swift-bridge]
actual interface ComposeViewFactory {

    fun createNativeScaffold(
        toolbar: Toolbar?,
        tabs: List<TabItem>,
        selectedTabPosition: Int,
        onTabSelected: (Int) -> Unit,
        content: (Int?) -> UIViewController,
    ): Pair<UIViewController, NativeScaffoldDelegate>
}
