package kmp.shared.sampletabbar.presentation.ui

import androidx.compose.runtime.ProvidableCompositionLocal
import androidx.compose.runtime.compositionLocalOf

// Originally generated by Touchlab's [compose-swift-bridge]
val LocalViewFactory: ProvidableCompositionLocal<ComposeViewFactory> =
    compositionLocalOf(
        defaultFactory = {
            error(
                """You have to provide LocalViewFactory""",
            )
        },
    )
