package kmp.shared.samplecomposemultiplatform.presentation.ui

import platform.UIKit.UIViewController

// Originally generated by Touchlab's [compose-swift-bridge]
actual interface ComposeSampleComposeMultiplatformViewFactory {
    fun createPlatformSpecificCheckboxView(
        text: String,
        checked: Boolean,
        onCheckedChanged: (Boolean) -> Unit,
    ): Pair<UIViewController, PlatformSpecificCheckboxViewDelegate>

    fun createScreenWithPlatformSpecificBottomBar(
        tabs: List<BottomBarTabForIos>,
        selectedTabPosition: Int,
        onSelectedTabChanged: (Int) -> Unit,
    ): Pair<UIViewController, ScreenWithPlatformSpecificBottomBarDelegate>
}
