package kmp.shared.samplecomposemultiplatform.presentation.ui

import androidx.compose.runtime.Composable
import platform.UIKit.UIViewController

// Originally generated by Touchlab's [compose-swift-bridge]
actual interface ComposeSampleComposeMultiplatformViewFactory {
    fun createPlatformSpecificCheckboxView(
        text: String,
        checked: Boolean,
        onCheckedChanged: (Boolean) -> Unit,
    ): Pair<UIViewController, PlatformSpecificCheckboxViewDelegate>

    fun createPlatformSpecificBottomBar(
        items: List<String>,
        selected: String,
        onSelectedChanged: (String) -> Unit,
        onSizeChanged: (Float, Float) -> Unit,
    ): Pair<UIViewController, PlatformSpecificBottomBarDelegate>

    fun createScreenWithPlatformSpecificBottomBar(
        tabs: Map<String, UIViewController>,
        selectedTab: String,
        onSelectedTabChanged: (String) -> Unit,
    ): Pair<UIViewController, ScreenWithPlatformSpecificBottomBarDelegate>
}
