name: iOS - Release

on:
  workflow_dispatch:
    inputs:
      alpha:
        type: boolean
        description: 'Alpha'
        default: true
      production:
        type: boolean
        description: 'Production'
        default: true

jobs:
  build:
    name: Create new builds
    runs-on:
      group: matee-tartelets
    timeout-minutes: 60
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          clean: false
      - name: Setup tools
        working-directory: ios
        run: ./scripts/setup.sh
      - name: Generate build number
        run: echo "BUILD_NUMBER=$(echo `date +"%y%m%d%H%M"`)" >> $GITHUB_ENV
      - name: Prepare App Store Connect API key file
        env:
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
        working-directory: ios
        run: echo "$APP_STORE_CONNECT_API_KEY_CONTENT" > AuthKey_Matee.p8
      - name: Create a new Alpha build
        if: ${{ github.event.inputs.alpha == 'true' }}
        working-directory: ios
        run: fastlane build_alpha
      - name: Create a new Production build
        if: ${{ github.event.inputs.production == 'true' }}
        working-directory: ios
        run: fastlane build_production
      - name: Create and push git tag
        working-directory: ios
        run: fastlane tag alpha:${{ github.event.inputs.alpha }} prod:${{ github.event.inputs.production }}
      - name: Cache build output
        uses: actions/cache@v4
        with:
          path: ios/ipa/
          key: ios-build-${{ github.sha }}-release  # Unique key based on the commit SHA

  deploy-alpha:
    name: Deploy alpha
    needs: build
    if: ${{ github.event.inputs.alpha == 'true' }}
    runs-on:
      group: matee-tartelets
    timeout-minutes: 120
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          clean: false
      - name: Restore cache for build output
        uses: actions/cache@v4
        with:
          path: ios/ipa/
          key: ios-build-${{ github.sha }}-release  # Unique key based on the commit SHA
      - name: Upload the Alpha build to the TestFlight
        env:
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
          SLACK_URL: ${{ secrets.FASTLANE_SLACK_URL }}
        working-directory: ios
        run: fastlane upload_testflight_alpha distribute_external:true
        
  deploy-production:
    name: Deploy production
    needs: build
    if: ${{ github.event.inputs.production == 'true' }}
    runs-on:
      group: matee-tartelets
    timeout-minutes: 120
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          clean: false
      - name: Restore cache for build output
        uses: actions/cache@v4
        with:
          path: ios/ipa/
          key: ios-build-${{ github.sha }}-release  # Unique key based on the commit SHA
      - name: Upload the Production build to the TestFlight
        env:
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
          SLACK_URL: ${{ secrets.FASTLANE_SLACK_URL }}
        working-directory: ios
        run: fastlane upload_testflight_production distribute_external:true
