name: iOS - Release

on:
  workflow_dispatch:
    inputs:
      alpha:
        type: boolean
        description: 'Alpha'
        default: true
      production:
        type: boolean
        description: 'Production'
        default: true
        
jobs:
  generate-build-number:
    name: Generate build number
    runs-on:
      group: matee-tartelets
    timeout-minutes: 5
    outputs:
      BUILD_NUMBER: ${{ steps.generate.outputs.BUILD_NUMBER }}
    steps:
      - id: generate
        run: echo "BUILD_NUMBER=$(echo `date +"%y%m%d%H%M"`)" >> "$GITHUB_OUTPUT"

  deploy_alpha:
    name: Build & Deploy Alpha
    if: ${{ github.event.inputs.alpha == 'true' }}
    runs-on:
      group: matee-tartelets
    timeout-minutes: 60
    needs: generate-build-number
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          clean: false
      - name: Setup tools
        working-directory: ios
        run: ./scripts/setup.sh
      - name: Prepare App Store Connect API key file
        env:
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
        working-directory: ios
        run: echo "$APP_STORE_CONNECT_API_KEY_CONTENT" > AuthKey_Matee.p8
      - name: Create a new Alpha build
        working-directory: ios
        env:
          BUILD_NUMBER:  ${{needs.generate-build-number.outputs.BUILD_NUMBER}}
        run: fastlane build_alpha
      - name: Upload the Alpha build to the TestFlight
        env:
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
          SLACK_URL: ${{ secrets.FASTLANE_SLACK_URL }}
        working-directory: ios
        run: fastlane upload_testflight_alpha distribute_external:true
        
  deploy_production:
    name: Build & Deploy Production
    if: ${{ github.event.inputs.production == 'true' }}
    runs-on:
      group: matee-tartelets
    timeout-minutes: 60
    needs: generate-build-number
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          clean: false
      - name: Setup tools
        working-directory: ios
        run: ./scripts/setup.sh
      - name: Prepare App Store Connect API key file
        env:
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
        working-directory: ios
        run: echo "$APP_STORE_CONNECT_API_KEY_CONTENT" > AuthKey_Matee.p8
      - name: Create a new Production build
        working-directory: ios
        env:
          BUILD_NUMBER:  ${{needs.generate-build-number.outputs.BUILD_NUMBER}}
        run: fastlane build_production
      - name: Upload the Production build to the TestFlight
        env:
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
          SLACK_URL: ${{ secrets.FASTLANE_SLACK_URL }}
        working-directory: ios
        run: fastlane upload_testflight_production distribute_external:true
      - name: Create and push git tag
        working-directory: ios
        run: fastlane tag alpha:false prod:true