name: iOS - Release

on: workflow_dispatch

jobs:
  build:
    name: Create new builds
    runs-on:
      group: matee-tartelets
    timeout-minutes: 60
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          clean: false
      - name: Build KMP
        working-directory: ios
        run: |
          ./scripts/generate-error-messages.sh
          ./scripts/build-kmp.sh release false true false
      - name: Setup tools
        working-directory: ios
        run: ./scripts/setup.sh
      - name: Generate build number
        run: echo "BUILD_NUMBER=$(echo `date +"%y%m%d%H%M"`)" >> $GITHUB_ENV
      - name: Prepare App Store Connect API key file
        env:
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
        working-directory: ios
        run: echo "$APP_STORE_CONNECT_API_KEY_CONTENT" > AuthKey_Matee.p8
      - name: Create builds
        working-directory: ios
        run: |
          fastlane build_alpha
          fastlane build_beta
          fastlane build_production
          fastlane tag
      - name: Cache build output
        uses: actions/cache@v4
        with:
          path: ios/ipa/
          key: ios-build-${{ github.sha }}-release  # Unique key based on the commit SHA

  deploy-alpha:
    name: Deploy alpha
    needs: build
    runs-on:
      group: matee-tartelets
    timeout-minutes: 120
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          clean: false
      - name: Restore cache for build output
        uses: actions/cache@v4
        with:
          path: ios/ipa/
          key: ios-build-${{ github.sha }}-release  # Unique key based on the commit SHA
      - name: Upload the Alpha build to the TestFlight
        env:
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
          SLACK_URL: ${{ secrets.FASTLANE_SLACK_URL }}
        working-directory: ios
        run: fastlane upload_testflight_alpha distribute_external:true

  deploy-beta:
    name: Deploy beta
    needs: build
    runs-on:
      group: matee-tartelets
    timeout-minutes: 120
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          clean: false
      - name: Restore cache for build output
        uses: actions/cache@v4
        with:
          path: ios/ipa/
          key: ios-build-${{ github.sha }}-release  # Unique key based on the commit SHA
      - name: Upload the Beta build to the TestFlight
        env:
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
          SLACK_URL: ${{ secrets.FASTLANE_SLACK_URL }}
        working-directory: ios
        run: fastlane upload_testflight_beta distribute_external:true

  deploy-production:
    name: Deploy production
    needs: build
    runs-on:
      group: matee-tartelets
    timeout-minutes: 120
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          clean: false
      - name: Restore cache for build output
        uses: actions/cache@v4
        with:
          path: ios/ipa/
          key: ios-build-${{ github.sha }}-release  # Unique key based on the commit SHA
      - name: Upload the Production build to the TestFlight
        env:
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
          SLACK_URL: ${{ secrets.FASTLANE_SLACK_URL }}
        working-directory: ios
        run: fastlane upload_testflight_production distribute_external:true
